modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="toendallplushies"
version="1.1.0"
displayName="ToEndAllPlushies"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="stein, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.toendallplushies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration